DROP SCHEMA public CASCADE;

CREATE SEQUENCE seq1 START WITH 1;

CREATE TABLE CUSTOMER (

   id BIGINT NOT NULL PRIMARY KEY,

   firstName VARCHAR(255) NOT NULL,

   lastName VARCHAR(255) NOT NULL,

   code VARCHAR (255)

);